### PR TITLE
Fix log for Execution cleanup history

### PR DESCRIPTION
**Pull request by carlosrfranco**
Fix execution cleaner that was not logging to the log files

### CODE REVIEW

**Comment by jtobard** [comment]
Log example of this change:
```
2019-05-17 11:45:00,004 INFO  ExecutionsCleanerJob - Initializing cleaner execution history job
2019-05-17 11:45:00,308 INFO  ExecutionsCleanerJob - Cleaner parameters: Project name: test_b
2019-05-17 11:45:00,308 INFO  ExecutionsCleanerJob - Max days to keep: 1
2019-05-17 11:45:00,308 INFO  ExecutionsCleanerJob - Minimum executions to keep: 0
2019-05-17 11:45:00,308 INFO  ExecutionsCleanerJob - Maximum size of deletions: 500
2019-05-17 11:45:00,432 INFO  ExecutionsCleanerJob - found 0 executions
2019-05-17 11:45:00,432 INFO  ExecutionsCleanerJob - No executions to delete
2019-05-17 11:45:00,433 INFO  ExecutionsCleanerJob - Executions to delete: []
2019-05-17 11:45:00,433 INFO  ExecutionsCleanerJob - Start to delete 0 executions
2019-05-17 11:46:00,001 INFO  ExecutionsCleanerJob - Initializing cleaner execution history job
2019-05-17 11:46:00,189 INFO  ExecutionsCleanerJob - Cleaner parameters: Project name: test_b
2019-05-17 11:46:00,189 INFO  ExecutionsCleanerJob - Max days to keep: 1
2019-05-17 11:46:00,189 INFO  ExecutionsCleanerJob - Minimum executions to keep: 0
2019-05-17 11:46:00,189 INFO  ExecutionsCleanerJob - Maximum size of deletions: 500
2019-05-17 11:46:00,271 INFO  ExecutionsCleanerJob - found 1 executions
2019-05-17 11:46:00,274 INFO  ExecutionsCleanerJob - Workflow execution: Workflow:(threadcount:1){ [] }
2019-05-17 11:46:00,274 INFO  ExecutionsCleanerJob - Executions to delete: [Workflow execution: Workflow:(threadcount:1){ [] }]
2019-05-17 11:46:00,274 INFO  ExecutionsCleanerJob - Start to delete 1 executions
2019-05-17 11:46:00,313 DEBUG ExecutionsCleanerJob - 2 files from execution will be deleted
2019-05-17 11:46:00,319 DEBUG ExecutionsCleanerJob - 2 files removed
2019-05-17 11:46:00,319 INFO  ExecutionsCleanerJob - Execution with ID 14229 were deleted
2019-05-17 11:46:00,320 INFO  ExecutionsCleanerJob - Deleted 1 of 1 executions

```

**Comment by ahonor** [comment]
Let's name ExecutionsCleanerJob -> ExecutionsCleanUp

**Comment by ahonor** [comment]
What does the log4j configuration look like?

**Comment by carlosrfranco** [comment]
> What does the log4j configuration look like?

You can enable all logs for INFO level or create a new appender like this:

`log4j.logger.rundeck.quartzjobs.ExecutionsCleanUp=INFO,cleanup
log4j.additivity.rundeck.quartzjobs.ExecutionsCleanUp=false


log4j.appender.cleanup=org.apache.log4j.DailyRollingFileAppender
log4j.appender.cleanup.file={dir_for_log4j_files}/logs${file.separator}rundeck.cleanup.log
log4j.appender.cleanup.append=true
log4j.appender.cleanup.layout=org.apache.log4j.PatternLayout
log4j.appender.cleanup.layout.ConversionPattern=%d{ISO8601} [%t] %-5p %c - %m%n`

**Comment by ahonor** [comment]
Creating a new appender is a great idea.

**Pull request merged**
