### PR TITLE
Change in the async call for SCM gui #4998

### LINKED ISSUE #4998: Unable to import SCM changes - URI is too large >8192
**Describe the bug**
I have a project with 240 jobs and I'm trying to confiugre SCM to import jobs. The rundeck UI never shows the notification for pending imports. It work well in other projects with fewer jobs

**My Rundeck detail**

* Rundeck version: 3.0.21.20190424-1.201904242241
* install type: deb
* OS Name/version: ubuntu 18.04
* DB Type/version:mysql

**To Reproduce**
1. Create a project
2. Add a lot of jobs (about 240 job)
3. Set up SCM to import jobs
4. Look the error on the browser console 

Request:
https://rundeck.<domain>/menu/listExport?project=Operations&nextScheduled=d98608ec-c90b-4bf8-82e9-42a9bd5c127f%2C01e374cb-8cfc-4770-b4cf-d9f616c329d8%2C3608778b-de3c-47f2-97ae-c09b2a37ed5c%2Cc3ed1138-b1ab-4356-a34d-b80d87c84b1f%2C403b34df-014c-44e0-a6f9-990162310458%2C5a5b6f6a-53f2-47e7-b04f-83885da47258%2Cd809bfa9-4be9-43cb-a2bf-095a45303c03%2C032c75c8-ca20-430a-b824-5d025ea45900%2C4336d6d1-77a7-4213-b99e-7ea36bbe820f%2Cdc9bc690-65d6-4c00-bef0-716e97b05971%2C5a003b52-55a1-45de-b88a-6f4296511d33%2Cb792166d-17a8-4dbe-bca6-ea0299a02769%2C851adeb3-0b4d-4963-a94b-8d73c7f9e0d1%2Ce8c057cf-a04b-4b49-b051-5d2417ebd863%2C3916c5cb-034f-4d74-94eb-85c8d2c7703b%2Cedbdfb67-168c-4c8d-887a-45d28e65e8b5%2C2c035972-cd1e-4bc2-bf64-3b224285d49d%2......

Response:
Bad Message 414
**reason: URI Too Long**

Server logs:
2019-06-26 18:06:54.644  WARN --- [qtp168947686-26] org.eclipse.jetty.http.HttpParser        : **URI is too large >8192**

### PR DESCRIPTION
**Pull request by jtobard**
Change the ajax call to `scmjobs` endpoint. Pass the data through the body of the ajax call instead of the URL to prevent 'URI is too large' problem.

fix #4998

### CODE REVIEW

**Comment by gschueler** [comment]
what are the changes to `self.messages`, that seems unrelated?

**Comment by jtobard** [comment]
`self.message` didn't exist and threw an error of `undefined` when going to look for the message that goes with the icon.
The right property is `messages`: https://github.com/rundeck/rundeck/blob/7a4df94774a065bfa19a97092fed5754341601bc/rundeckapp/grails-app/assets/javascripts/menu/jobs.js#L47

**Comment by gschueler** [comment]
ok, but it should be a separate pr then

**Comment by jtobard** [comment]
@gschueler is not possible to check the current fix without that change, because the javascript exception prevent anything else of the SCM async call to work

**Comment by jtobard** [comment]
I'm closing this PR to create a new issue and two separate PRs

**Comment by jtobard** [comment]
PRs: https://github.com/rundeck/rundeck/pull/5076
https://github.com/rundeck/rundeck/pull/5075

**Pull request closed without merging**
