### PR TITLE
Enh/UI updates

### PR DESCRIPTION
**Pull request by mishingo**
**Is this a bugfix, or an enhancement? Please describe.**
Bugfix and Enhancement: Addresses bugs in darkmode and enhances certain aspects of the UI

**Describe the solution you've implemented**
- Update Webhook Layout to match System Config
- Fix Button Colors in darkmode
- Add Css Modifiers
- Bring Job Create to the front
- add pointer to hover on dropdown
- add spacing to activity batch delete buttons

### CODE REVIEW

**Comment by mishingo** [comment]
image

**Comment by mishingo** [comment]
image

**Comment by mishingo** [comment]
Tooltip for key storage:
image

**Comment by mishingo** [comment]
image

**Comment by mishingo** [comment]
image
Spacing Bulk Delete Actions

**Comment by mishingo** [comment]
image
Broken Dark Button

**Comment by mishingo** [comment]
image
fixed in firefox

**Review by carlosrfranco — APPROVED** [review]
LGTM

**Pull request merged**
