### PR TITLE
This adds dattepicker functionality.

### PR DESCRIPTION
**Pull request by bajacondor**
*A new job option type that is a date and uses the datepicker to select it.
*Datepicker widgets to filter the activity reports

### CODE REVIEW

**Comment by gschueler** [comment]
Thanks!
I see references to these files, but they are not included:
* jquery-ui-timepicker-addon.js
* jquery-ui.css
* jquery-ui.js

**Comment by bajacondor** [comment]
Oops. You're right.  I'm new to github pull-requests.

**Comment by dbollaer** [comment]
Is there any news about this issue? I would like to use this in one of my projects.

**Comment by gschueler** [comment]
merged with some modifications:

* use bootstrap datetime picker for Job option value selection
* add `dateFormat` field for options

**Pull request merged**
