### PR TITLE
Adds global parameters

### PR DESCRIPTION
**Pull request by miguelantonio**
Adds global parameters using framework.properties defined parameters, in that file as framework.globals.VAR, in rundeck as ${globals.VAR}

### CODE REVIEW

**Comment by miguelantonio** [comment]
@ahonor @gschueler Global params up and running

**Comment by gschueler** [comment]
@miguelantonio cool, can you add some unit tests of the functionality?

**Comment by miguelantonio** [comment]
@gschueler of course we will add them

**Comment by gschueler** [comment]
close in favor of https://github.com/rundeck/rundeck/pull/1890

**Pull request closed without merging**
