### PR TITLE
Fix rundeckd init script

### PR DESCRIPTION
**Pull request by tuladhar**
Made changes to display rundeckd when checking status of rundeckd daemon. Please, review.

```shell
# /etc/init.d/rundeckd status
java (pid  24682) is running...
```
__Fix:__
```shell
# /etc/init.d/rundeckd status
rundeckd (pid  24682) is running...
```

### CODE REVIEW

**Comment by ahonor** [comment]
Thanks

**Comment by ahonor** [comment]
TODO: Update launcher and deb rundeckd script

**Comment by tuladhar** [comment]
Thanks for the merge. :+1: 

deb and launcher script looks good, no updates required :)

__Launcher:__
```shell
[rundeck]# $RDECK_BASE/server/sbin/rundeckd status
Status rundeckd: rundeckd is running (pid=17074, port=4440)
```
__Debian:__
```shell
root@debian-7-5:~# /etc/init.d/rundeckd status
[ ok ] rundeckd is running.
```

**Comment by ahonor** [comment]
Thanks for checking!

**Pull request merged**
