### PR TITLE
Rundeck init scripts updates

### PR DESCRIPTION
**Pull request by hmalinov**

### CODE REVIEW

**Comment by acasademont** [comment]
+1, the current scripts are pretty terrible, spawning 2 processes. Also, maybe a systemd unit file should be bundled instead of the old init script...

**Comment by acasademont** [comment]
@gschueler this works like a charm btw, we've been using this init script for a while now

**Comment by acasademont** [comment]
HI @gschueler any updates on this one? Been using it for over 2 months and works flawlessly (besides #2498 which doesn't have to do with this at all)

**Comment by hmalinov** [comment]
Fixed the conflict.

**Comment by jtobard** [comment]
I have tried and it works to me, I implement the changes to the last version on my master, run the tests, install it on a clean environment, it starts, restarts and stops as expected.

**Pull request merged**
