### PR TITLE
Remove random 'e' character

### PR DESCRIPTION
**Pull request by danielabbatt**
I was just browsing the code and spotted what appears to be a random 'e'.

### CODE REVIEW

**Comment by gschueler** [comment]
folks, that's not just any random 'e'; that file with random 'e' was committed by me 10 years ago when i created the initial import of rundeck, which was based off an earlier project.  That 'e' might be older than that!

**Comment by gschueler** [comment]
I tracked down the original commit: 4/20/2010 : https://sourceforge.net/p/controltier/code/9891/

thank you @danielabbatt 😆

**Comment by jessemarple** [comment]
It is with great pleasure that I merge this pull request on code that Greg believes might be older than 10 years in the project. 🍾

**Comment by danielabbatt** [comment]
Haha - glad to be of help!

**Pull request merged**
