### PR TITLE
DD/MM/YYYY and 24h format for dates and time

### PR DESCRIPTION
**Pull request by danifr**
https://github.com/rundeck/rundeck/issues/1342

I added this new messages file. Since I only modified date and time format, I named it messages_**en-gb**.properties (english + _european_ date format + 24h time format)

If there is a better way to do it please let me know and I'll be happy to change it.

### CODE REVIEW

**Comment by gschueler** [comment]
Does it work to include only the modified messages, i.e. just the date format entries, instead of duplicating all of the other messages as well?

**Comment by danifr** [comment]
Hi Greg,

I'm not sure about it. Unfortunately, all my Rundeck servers are using the en_US locale, so I'm modifying directly `/var/lib/rundeck/exp/webapp/WEB-INF/grails-app/i18n/messages.properties`

For this test, I changed the machine's locale to en-GB but nothing changed after restating Rundeck, so I guess there is something wrong with my config.

**Comment by gschueler** [comment]
@danifr I've noticed that grails will actually render pages using the locale requested by the web client browser, so if your browser says your locale is US, that's what response it will use.  You can try adding `?lang=en-GB` to the URL in your browser

**Comment by ssbarnea** [comment]
Have a look at https://github.com/rundeck/rundeck/issues/1682#issue-133928883 -- which must be fixed ASAP. Unless RunDeck aims on being a US-only product.

**Comment by gschueler** [comment]
Hi, thank you for submitting this change.  👏  I apologize that it was not addressed in a timely fashion 😢, we are working to improve the way we handle PRs. 

If you are still interested in proposing this change, please feel free to reopen the request.  Since it has been some time since it was opened, your code might be now out of date.  If so, please try to rebase your changes on the latest `master` branch.

One change we added was support for selecting the user language in the GUI (under the User > Profile) link.

Thank you!

**Pull request closed without merging**
