### PR TITLE
removed UUID validation of jobRef

### LINKED ISSUE #4451: Importing project archive fails if referenced job name/group changed
**Describe the bug**
Projects with jobs referenced by UUID that have had their names or groups updated will cause import failures with "Preserve UUID".

**My Rundeck detail**

* Rundeck version: 3.0.13
* install type: Docker

**To Reproduce**
1. Import the project into one instance
2. Rename `RefMe` or its group
3. Export the project and import into another Rundeck instnace

**Expected behavior**
Rundeck should continue to allow me to export and import projects even if I have renamed referenced jobs or their groups.

**Screenshots**
image

**Additional context**
The error message does not explain the problem or offer a workaround. The logs are the only indicator of the issue:
```
2019-02-04 22:48:45.258 ERROR --- [tp2031149831-30] rundeck.services.ProjectService          : Failed loading (1) jobs from XML at archive path: rundeck-ProjectA/jobs/job-a6d88d66-920b-492b-b7c4-1a22da67333b.xml
2019-02-04 22:48:45.259 ERROR --- [tp2031149831-30] rundeck.services.ProjectService          : Job at index [1] had errors: Validation errors: Workflow has one or more invalid steps: [1: [Job Name does not correspond to the UUID]]; Invalid Option definition: Foo: Workflow has one or more invalid steps: [1: [Job Name does not correspond to the UUID]]
```

[ProjectA-20190204-225828.rdproject.zip](https://github.com/rundeck/rundeck/files/2830123/ProjectA-20190204-225828.rdproject.zip)

### PR DESCRIPTION
**Pull request by jtobard**
Job reference step using UUID and job name pointing to a job that doesn't exist won't fail it will only remove the `UUID` component and leave just the `jobname` reference.

Fix #4451 and 4471

### CODE REVIEW

**Comment by ProTip** [comment]
@jtobard  are you able to import the archive from #4451 ? I seem to be unable to import it on anything above `3.0.12`, including a build of this branch.. It's odd because the job name and UUID match the referenced job in that archive..

**Comment by jtobard** [comment]
@ProTip my mistake, missing some code on the PR maybe because I moved from another branch by hand, now pushing it.

**Comment by gschueler** [comment]
@jtobard perhaps there needs to be a functional test performing the import

**Comment by ProTip** [comment]
@jtobard Thanks! I have tested this and it does let me import the project, as well as the project if a referenced job has been renamed.

It seems though that the Job names are getting stripped(instead of just ignored for validation purposes). After I import the example project where everything matches, and I view the reference workflow step, only the UUID remains in GUI. Without looking up the name and displaying it users may be surprised that the reference names are gone after an import?

I'm also curious that in the case of #4471 if we strip the UUID when importing jobs out of order, will this leave only the job name? In that case if a job has been renamed or regrouped the UUID may actually be correct and leaving just the name as reference may break the workflows.

**Pull request merged**
