### PR TITLE
RSE-406:: LDAP Fix huge number of groups

### PR DESCRIPTION
**Pull request by avelasquezr**
## Describe Bug
LDAP: error code 4 - Sizelimit Exceeded when you activated the nestedGroups option and you had a large number of groups.

## Before fix:
image

## After fix:
image

#### All 1014 members can be obtained..

### CODE REVIEW

**Review by alexander-variacode — COMMENTED** [review]
Add the unit test of your change

**Comment by avelasquezr** [comment]
> Add the unit test of your change

There already existed 3 unit tests that covered the case. The necessary mocks are added to keep them working.

**Review by alexander-variacode — COMMENTED** [review]
Add a test on JettyCachingLdapLoginModuleTest instead of JettyCachingLdapLoginModuleTest2. The idea is to have the new features/fixes testing on Spock.

**Review by alexander-variacode — APPROVED** [review]
LGTM

**Pull request merged**
