### PR TITLE
Add job.executionType context variable

### PR DESCRIPTION
**Pull request by ctrlrsf**
Currently there's no way to differentiate whether a job was ran by a user
and a job ran by the scheduler by looking at the job context variables.

With this change, we'll have a job.executionType context variable that will
indicate what invoked the job.

Possible values of job.executionType:
  adhoc = adhoc command
  user = job initiated by a user
  scheduled = job triggered by the scheduler

This is a first stab at this problem to get the ball rolling.

Please review for correctness and let me know if anything
else is needed.

Addresses issue https://github.com/rundeck/rundeck/issues/1811

Signed-off-by: Rene Fragoso ctrlrsf@gmail.com

### CODE REVIEW

**Comment by gschueler** [comment]
thanks, looks like a good start!  setting the `execution.executionType` in ExecutionJob.groovy may need to be changed, ideally it should be set when the Execution is created, just so there is no need to do another .save() to the db. I think it will be easy, the executions are created by ExecutionJob for scheduled jobs only, for all other cases, the executions are created ahead of time, and so it should be easy to tell what value to use when.

**Comment by ctrlrsf** [comment]
Hi @gschueler. I've updated my PR to set the executionType when Execution is created. Can you confirm it's on the right track? Thanks!

**Comment by gschueler** [comment]
@ctrlrsf looks good so far.  the other place that `createExecution` is called is when an execution is retried here: https://github.com/rundeck/rundeck/blob/development/rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy#L1595

however, retried executions are already marked as retried from previous executions, so not sure if executionType is necessary to set

**Comment by ctrlrsf** [comment]
@gschueler thanks for the additional comments. I updated PR to pass through the executionType when a job is retried.

**Comment by gschueler** [comment]
@ctrlrsf great, the only other thing I would request is if you could add some unit tests, but otherwise i think it looks good

**Comment by ctrlrsf** [comment]
@gschueler I've added two tests to confirm executionType is being set properly. 

I also modified the code to be more straight forward. Now executionType is set to "scheduled" by default when an Execution object is created.

When a user runs a job from the web using Run Now button, ScheduledExecutionController.runJob() function will set an executionType input option to "user", which will eventually get passed as the executionType property when Execution object is later created.

Let me know if you have any further comments.

**Pull request merged**
