### PR TITLE
Making improvements for the cleaner executions history scheduler

### PR DESCRIPTION
**Pull request by carlosrfranco**
This changes include: 

* Default values for clean executions history scheduler
* GUI validations for fields
* Select with some preset cron values
* An API test

### CODE REVIEW

**Comment by gschueler** [comment]
@carlosrfranco try to rebase your branch on master, the deb build/test was updated

**Comment by jtobard** [comment]
Can you add `execution.history. cleanup.label=Execution History Clean:` to the messages.properties file to make easier to translate later?

And change it on `_editProjectForm.gsp` to reflect the naming convention.

**Comment by carlosrfranco** [comment]
> Can you add `execution.history. cleanup.label=Execution History Clean:` to the messages.properties file to make easier to translate later?
> 
> And change it on `_editProjectForm.gsp` to reflect the naming convention.

It was just added. But I'll push more changes for it now

**Comment by ahonor** [comment]
Saving history clean does not seem to work.

**Comment by ahonor** [comment]
What file does the history clean log it's activity?

**Comment by carlosrfranco** [comment]
> What file does the history clean log it's activity?

The logs are not being written to the file as I thought they would be. I've created a new PR to address this differently: https://github.com/rundeck/rundeck/pull/4834

**Pull request merged**
