### PR TITLE
job definition io component extension

### PR DESCRIPTION
**Pull request by gschueler**
**Is this a bugfix, or an enhancement? Please describe.**

Refactor job definition loading/exporting, and creating via gui, to support componentized internal pattern.

**Describe the solution you've implemented**

Allow internal components to handle individual portions of job definitions. Clean up current messy job definition handling in ScheduledExecutionService.

**Todos**

- [x] components can contribute to job definition import/export. 
    - [x] refactor old XML/Yaml Codec implementations into JobFormat implementations
    - [x] allow direct "canonical map" conversion for yaml, and modified "xmap" conversion for xml
- [x] components can receive input from web when creating jobs
- [x] refactor job *create* to work with new imports
- [x] refactor job *update* to work with new imports
- [x] handle job delete
- [x] allow custom UI props for components
- [x] allow validation reports
- [x] show validation data in gui

### CODE REVIEW

**Comment by ronaveva** [comment]
Export job as yaml is not working, JobsYAMLCodec is using a new instance of "RundeckJobDefinitionManager", hence applicationContext is null

**Comment by gschueler** [comment]
@ronaveva should be fixed now

**Comment by ronaveva** [comment]
It is not showing the validation error messages when importing a job

imagen

**Comment by ltamaster** [comment]
Using a job with options, when you save the job (without modifying any option), all the options just disappear.

**Pull request merged**
