### PR TITLE
Execution Metrics API

### PR DESCRIPTION
**Pull request by ahormazabal**
created two new API endpoints:
/api/V/project/[PROJECT]/executions/metrics
/api/V/executions/metrics (system-wide variant)

Both APIs receive the same parameters as the Execution Query API, but returns statistics over the execution resultset instead of returning the actual executions.

Current stats implemented:
- Count of total executions.
- Count by each execution state
- Average execution duration.
- Maximum execution duration.
- Minimum execution duration.

### CODE REVIEW

**Comment by gschueler** [comment]
Looks good to me, can you add API documentation with a PR to @rundeck/docs ?

**Comment by ahormazabal** [comment]
Added documentation on PR https://github.com/rundeck/docs/pull/192.
Also i have updated the branch to be mergeable with master.

**Comment by ahormazabal** [comment]
Please also review the corresponding CLI commands on https://github.com/rundeck/rundeck-cli/pull/210

**Comment by gschueler** [comment]
@ahormazabal i've played with the changes a bit, I think I will update it with these changes if you don't mind:

change the output model:

~~~.json
{
  "duration": {
    "average": "1s",
    "min": "0s",
    "max": "39s"
  },
  "total": 97,
  "status": {
    "failed-with-retry": 48,
    "aborted": 1,
    "failed": 16,
    "succeeded": 32
  }
}
~~~

**Comment by ahormazabal** [comment]
looks great!

**Comment by gschueler** [comment]
todos

* [ ] update docs
* [ ] update rd tool

**Pull request merged**
