### PR TITLE
fix: grails-spa build, don't include extraneous assets

### PR DESCRIPTION
**Pull request by gschueler**
**Is this a bugfix, or an enhancement? Please describe.**

the rundeckapp/grails-spa build was including extraneous files (jars) in the assets dir

**Describe the solution you've implemented**

Update node based gradle build for grails-spa to use gradle base plugin, define archives, and update the rundeck app grails build to only copy the correct assets.

### CODE REVIEW

**Comment by ProTip** [comment]
@gschueler I just noticed these artifacts popping up when I re-based and tested a different branch. Do you know if these are getting built as part of a different, recent change to the build scripts?

**Comment by gschueler** [comment]
@ProTip i'm not sure when it started.  I think it is happening because of the gradle/java.gradle file which is applied to all subprojects in the root build.gradle, causing extra jars to be created in rundeckapp/grails-spa build dir.

**Comment by gschueler** [comment]
ok i think i fixed the gradle issues... now the deb install test is failing because it can't install oracle jdk 8 😢

**Comment by ProTip** [comment]
Looks like possibly a transient error. Saw a similar error last time oracle/webupd8team updated the package..

**Pull request merged**
