### PR TITLE
RUN-1374: job json format

### PR DESCRIPTION
**Pull request by gschueler**
**Is this a bugfix, or an enhancement? Please describe.**
enhancement: Adds a JSON format for job definitions

**Describe the solution you've implemented**
* add a JSON format definition class for Jobs
* enable JSON format input/output for API
* enable JSON format job definition download in GUI
* enable JSON format job definition upload in GUI
* update Git plugin to support JSON format

### CODE REVIEW

**Comment by sjrd218** [comment]
Looks like a great addition.

**Review by ahormazabal — APPROVED** [review]
Works ok!

**Comment by gschueler** [comment]
@mergifyio rebase

**Comment by gschueler** [comment]
docs pr https://github.com/rundeck/docs/pull/1182

**Pull request merged**
