### PR TITLE
RUN-708: Cannot uncheck the "Keep going on success" option for error handler

### PR DESCRIPTION
**Pull request by alexander-variacode**
Issue:
https://github.com/rundeckpro/rundeckpro/issues/2267

Fix description:
When the property keepgoingonsuccess is not sent by the front-end this is set as false.

### CODE REVIEW

**Review by L2JE — APPROVED** [review]
LGFM

**Comment by fdevans** [comment]
Needs tests per @gschueler

**Comment by gschueler** [comment]
can you add a test to verify the behavior?

**Comment by alexander-variacode** [comment]
@Mergifyio rebase

**Review by gschueler — APPROVED** [review]

**Pull request merged**
