### PR TITLE
Preauthentication filter

### PR DESCRIPTION
**Pull request by tlots**
Hi,

Thanks to the team for all of the work you’ve put into this project. 

Here is a contribution towards preauthenticating with a reverse proxy, works towards resolving #1229 - Feedback is appreciated.

We are currently using https://github.com/bitly/oauth2_proxy to auth with Github and send a remote user and roles (as defined by teams) along to Rundeck. I’ve written a Spring filter that intercepts the request object at the beginning of the filter chain and modifies it to be sent along. 

There are a number of manual configuration changes. Here are the steps we take for `rundeck-launcher`

* Set `rundeck.security.authorization.preauthenticated.enabled=true`
* Build the project
  `$ ./gradlew clean build` 
* Run jar with install option on (default)
 `$ java -jar rundeck-launcher/launcher/build/libs/rundeck-launcher-2.6.8-SNAPSHOT.jar --install-only` 

* Modify `rundeck-launcher/launcher/build/libs/server/exp/webapp/WEB-INF/web.xml` 

 * Add the filter to the top of the filter chain.
    
```
<filter>
    <filter-name>AuthFilter</filter-name>
    <filter-class>com.dtolabs.rundeck.server.filters.AuthFilter</filter-class>
</filter>
<filter-mapping>
    <filter-name>AuthFilter</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>
``` 
  
 *  Remove the `auth-constraint` element
  
```
<auth-constraint>
    <role-name>*</role-name>
</auth-constraint>
```  
  
* Run the jar again, this time use --skip-install to avoid overwriting the new web.xml

 `$ java -jar rundeck-launcher/launcher/build/libs/rundeck-launcher-2.6.8-SNAPSHOT.jar --skipinstall` 

Improvements / todo,

* Automate some of the manual configuration of web.xml above (we are doing it with our provisioning scripts).
* Access `preauthenticated.attributeName` value to be set from config in `AuthFilter`.
* Understanding and support of other use cases.

### CODE REVIEW

**Comment by gschueler** [comment]
So some ideas for the todos:

> Automate some of the manual configuration of web.xml above (we are doing it with our provisioning scripts).

I would like to take that step out altogether.  For the [DisablingAdminServlet](https://github.com/rundeck/rundeck/blob/master/rundeckapp/metricsweb/src/groovy/org/grails/plugins/metricsweb/DisablingAdminServlet.groovy) We add the servlet into the built web.xml to always be configured (via a grails plugin), yet it uses the Grails configs to determine whether it should actually do anything.  If we added the AuthFilter that way, it would only require a config change to enable/disable it.

> Access `preauthenticated.attributeName` value to be set from config in `AuthFilter`.

This can be done in the same was as DisablingAdminServlet.

**Comment by gschueler** [comment]
oops, the `auth-constraint` change would still be a manual step tho

**Comment by tlots** [comment]
@gschueler We've got the preauth enable/disable configuration logic written and in testing. I am assuming that writing a Grails plugin to inject the AuthFilter into the web.xml is the proper way to make that modification, is that correct?

**Comment by gschueler** [comment]
@tlots yes.  Looking forward to it! 👍

**Comment by tlots** [comment]
I've added a Grails plugin that modifies the web.xml to inject the AuthFilter, configuration for enabling and defining a redirect location which in our case is oauth2_proxy's logout endpoint, and intra-session updating of roles for the user from the upstream authentication system.

**Comment by gschueler** [comment]
very cool, do you have an example setup using oath2_proxy you can share?

**Comment by cjpetrus** [comment]
+1 for the example setup

**Comment by cjpetrus** [comment]
@tlots  please.... lol,  I would love to see this PR get merged.

**Comment by tlots** [comment]
Hi @gschueler and @cjpetrus, will be glad to share a full example as soon as it can be prepared. In the meantime, here are some notes to get you started:

We've done some work on oauth2_proxy to forward Github teams as roles. I plan on creating a PR to move those efforts upstream soon.
The fork is here - https://github.com/kindlyops/oauth2_proxy/commits/github-teams-tweaks

On the oauth2_proxy side,
+ Configuring `pass-roles-header` will pass the roles to Rundeck, which AuthFilter maps to `REMOTE_USER_GROUPS`.
+ Using `cookie-refresh` for the Github provider allows for role updates without the need for a new session; modifications were made to Rundeck's AuthorizationFilter to accommodate this enhancement.

In terms of Rundeck configuration,

+ The instructions in the top comment are mostly relevant with the following exceptions,
+ Configuration of a logout URL for the preauth method:
`rundeck.security.authorization.preauthenticated.redirectLogout=false
 rundeck.security.authorization.preauthenticated.redirectUrl=/oauth2/sign_in`

+ Adding AuthFilter to web.xml has been automated
+ `preauthenticated.attributeName` is configurable

**Comment by cjpetrus** [comment]
@tlots Thank you, I'm using nginx in front of oauth_proxy and passing a user's google groups along to outh_proxy via an X-Forwarded-Roles header. Thank you for your work on this issue, the community appreciates it!

**Comment by tlots** [comment]
I spoke with @cjpetrus elsewhere and he got it working on his own, but still wanted to share this gist of the two pertinent configuration files: https://gist.github.com/tlots/730a123054b9a737b78cf59661bd3274

**Comment by cjpetrus** [comment]
@statik @tlots @gschueler I merged this PR onto my fork, all is well. I'm also using a flask call back in a container to send specific google groups headers over as roles. This allows me to setup an acl policy. I'll share my configuration when I get  a chance.

**Comment by donaldguy** [comment]
I posted a gist here: https://gist.github.com/donaldguy/eaa99fb0d1f17c0576255c3cf3ffc7ea

for using https://github.com/grammarly/rocker to build a container containing the kindlyops fork of oauth2_proxy and running it with rundeck per the runtime configuration of https://github.com/jjethwa/rundeck

**Comment by amontalban** [comment]
@cjpetrus would be awesome if you can share your config using Google groups as roles as I'm trying to do the same. Thanks in advance!

**Comment by Akhena** [comment]
Hi everybody,

This feature is incredibly useful in some enterprises environments like ours. Thanks to this PR, we are now able to feed authentication to Rundeck from our existing reverse proxy.

We have now one last issue to sort before being able to roll out the preauthentication version : api consumption, by using api tokens.
And we tried is to generate an api token with an administrator account. But using that token when calling the api does not seem to work, we have zero authorizations.

When using preauthentication scenario, how are api tokens supposed to work?

Any tip you could give us will be precious!

**Comment by haseebeqx** [comment]
for google, also follow the steps mentioned here https://github.com/bitly/oauth2_proxy#google-auth-provider

**Pull request merged**
