### PR TITLE
Add metrics to API, update to APIv25

### PR DESCRIPTION
**Pull request by gschueler**
paths: /api/25/metrics  - list of metric hrefs

/api/25/metrics/{metrics,ping,threads,healthcheck} - endpoints

configuration, the servlets must be enabled for each endpoint, plus
api must be enabled for each endpoint

rundeck.web.metrics.servlets.$endpoint.enabled=true
rundeck.api.metrics.$endpoint.enabled=true

TODO:

- [x] access control?
- [x] unit tests
- [x] api functional tests
- [x] documentation

### CODE REVIEW

**Comment by gschueler** [comment]
Previously we had configuration to enable each metrics *servlet*, like `rundeck.web.metrics.servlets.[name].enabled=true/false`, however the metrics servlets were not very useful by themselves without API access.  Now that I've enabled API access, should that config be replaced with an API specific one, and the previous use of servlets directly be removed?

**Comment by gschueler** [comment]
Documentation pr: https://github.com/rundeck/docs/pull/33

**Comment by lukasged** [comment]
by chance, is there a way to enable anonymous access to the `/api/25/metrics/healthcheck` endpoint?

**Comment by monsdar** [comment]
Late to the party, but as I stranded here: Anonymous access to health-check is available at /health now. Docs: https://docs.rundeck.com/rundeck-cloud/administration/cluster/loadbalancer/health-check.html

**Pull request merged**
