### PR TITLE
Updating mode-yaml.js to later version and fixing to handle a variable when undefined.

### PR DESCRIPTION
**Pull request by carlosrfranco**
Fixes https://github.com/rundeckpro/rundeckpro/issues/1432

**Is this a bugfix, or an enhancement? Please describe.**
The javascript that handle yaml format on editor has a bug when typed a character like a pipe ` | ` is causing an error when calling a function from an undefined variable.
 
**Describe the solution you've implemented**
In addition to updating the mode-yaml.js script to the latest version, I made a small change to handle the variable if it is undefined. `r = r.replace` to `r = r? .replace`

### CODE REVIEW

**Comment by ltamaster** [comment]
@carlosrfranco 
I tested it and it worked, I am wondering if we need to upgrade the full ace library

**Comment by carlosrfranco** [comment]
@ltamaster 
do you mean the ace-builds on package.json?

**Comment by ltamaster** [comment]
I mean the files on https://github.com/rundeck/rundeck/blob/main/rundeckapp/grails-app/assets/javascripts/ace
for example ace.js

what do you think @ProTip ?

**Comment by ProTip** [comment]
@carlosrfranco @ltamaster Is there a way to resolve the issue without modifying the Ace code? It's really hard to verify the source and integrity of these vendored files even if they haven't been changed :) It's also hard to review and reason about exactly what the function does and what the implications of modifying it are..

Also, I believe that optional chaining operator is not the best choice; support was recently added to browsers and I know some users are on extended support versions of Chrome and Firefox that it won't work with.

**Comment by ProTip** [comment]
RE: Upgrade: It might be a good idea to upgrade it all. We could do it from an ace-builds tag, note the tag in the README, and that way would have a way to verify the source of the files and their integrity.

**Comment by carlosrfranco** [comment]
@ProTip Yes, I agree, modifying a third party file is not the best way but I don't know if it is possible to solve it in another way. It is worth investigating. If the only possible fix for this issue is in the code of vendored files, perhaps the other option would be to create a PR in their repository and wait for a new version?

**Comment by ProTip** [comment]
UPDATE: I think there may be something else going on here as it works fine with their online demo:

image

**Comment by ProTip** [comment]
@ltamaster @carlosrfranco Upgrading `ace.js` and `ext-language_tools.js` appears to work without modifying the code. I think maybe we should go ahead and upgrade..

**Comment by ltamaster** [comment]
sounds good to me, I tested the upgrade too and worked.

**Comment by carlosrfranco** [comment]
@ltamaster @ProTip done. Can you try it now?

**Comment by ProTip** [comment]
Can we upgrade all the modes/files?

**Comment by carlosrfranco** [comment]
> Can we upgrade all the modes/files? I think that may be best to avoid any incompatibilities.

It's true... I'm going to upgrade all this files

**Comment by carlosrfranco** [comment]
@ProTip It's done. Must be well tested to see if there was an impact elsewhere on the Rundeck

**Comment by ProTip** [comment]
@ltamaster Looks like the indentation was off a bit causing the shasum not to match. I've updated them, verified the shasums, and updated the README to include the Ace Build version. Could you approve if it all looks good to you?

**Review by ltamaster — APPROVED** [review]
tested

**Pull request merged**
