### PR TITLE
Fix: deleted jobs not reflected in project synch state

### PR DESCRIPTION
**Pull request by gschueler**
* happens if jobs deleted out of band of job events, i.e. other cluster member

**Is this a bugfix, or an enhancement? Please describe.**
fixes https://github.com/rundeckpro/rundeckpro/issues/1688

**Describe the solution you've implemented**
cache job id and file path within the plugin, track list of jobs refreshed during bg process. If some job ids are missing during bg refresh, and were previously cached in the plugin, remove the local files to reflect the deleted status.

**Additional context**
Add any other context or screenshots about the change here.

### CODE REVIEW

**Review by ltamaster — APPROVED** [review]
tested

**Comment by ronaveva** [comment]
deletion working correctly

**Review by ronaveva — APPROVED** [review]
LGTM

**Comment by ronaveva** [comment]
@gschueler i've found a small thing. When a deletion is made in cluster
1.-Cluster member where the job was deleted: shows job name deleted
2.-Other members: instead of showing the job name, only shows "(Deleted job)"

imagen

**Comment by gschueler** [comment]
@ronaveva yes, I saw that. I think it is ok for this pr. We could enhance it in the future to fix that I think, we would need to cache job details (name/group) along with the path when the bg process scans jobs

**Comment by gschueler** [comment]
i force pushed a change, it removes the change to the ScmExportPlugin, and allows the job name to show up correctly in the second cluster member

**Pull request merged**
