### PR TITLE
Fixes #5117 - getting back the tags to select target nodes for jobs execution

### LINKED ISSUE #5117: TAGS are no longer available
**Describe the bug**
The TAGS are no longer available in the jobs.

**My Rundeck detail**

* Rundeck version: 3.1.0
* install type: war (with tomcat 9)
* OS Name/version: RHEL 7.6
* DB Type/version: oracle

**To Reproduce**
Job Source:
[S_E_Kill_mstr_adm.zip](https://github.com/rundeck/rundeck/files/3457596/S_E_Kill_mstr_adm.zip)

**Expected behavior**
List of TAGS

**Screenshots**
2019-08-01 17_53_34-SWAT DVLP Rundeck - S_E_Kill mstr_adm

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 60.8.0esr

### PR DESCRIPTION
**Pull request by carlosrfranco**
Fix #5117 that request to return tags filter to select target nodes

**Is this a bugfix, or an enhancement? Please describe.**
Tags filter to select target nodes for jobs executions was removed from the GUI

**Describe the solution you've implemented**
Get back the tags filter to select target nodes.

### CODE REVIEW

**Comment by MegaDrive68k** [comment]
Testing the fix,  the tags keep marked if I select and later press "unselect all". 

1) Select a node using tags (works perfectly)

Screenshot_1

2) then click on "Select None" (the tag keeps marked but all nodes are unselected)

Screenshot_4

**Comment by MegaDrive68k** [comment]
A new test with a new SNAPSHOT, now the previous issue (https://github.com/rundeck/rundeck/pull/5616#issuecomment-569304079) disappears.

**Comment by gaddman** [comment]
Great to see this feature back! I'm seeing an error when there are 10 or more tags though. A button pops up with `Show All...` but clicking does nothing and generates a Javascript error:

Firefox 72.0.1:
`TypeError: Element.show is not a function`

Chrome Version 79.0.3945.117:
`Uncaught TypeError: Element.show is not a function
    at HTMLSpanElement.onclick (jobs:1)`

Should I log a new issue for this or track here?

**Comment by carlosrfranco** [comment]
@gaddman Please, log a new issue for this. Thank you

**Pull request merged**
