### PR TITLE
added web.xml to rpmbuild spec so it doesnt get replaced on update

### PR DESCRIPTION
**Pull request by mdorenkamp**
fixes https://github.com/rundeck/rundeck/issues/1590

### CODE REVIEW

**Comment by zionio** [comment]
+1

**Comment by beelzetron** [comment]
+1 on this one.

**Comment by mdorenkamp** [comment]
will this ever be merged? updating rundeck still causes big pains because of this non-merged PR

**Comment by ahonor** [comment]
+1

**Pull request merged**
