### PR TITLE
Fixes #5006 - ui issues in workflow editor

### LINKED ISSUE #5006: GUI: job workflow editor has visual problems
**Describe the bug**

UI issues in job workflow and options editor in 3.1

1. loading never goes away after edit/create an option
2. misaligned text in option listing
3. bg color beige should change to gray
4. after adding a new step, the border is not shown
5. weird padding in dropdown for step controls

**My Rundeck detail**

* Rundeck version: 3.1-snapshot

** screenshot **

Screen Shot 2019-06-27 at 11 32 48 AM

### PR DESCRIPTION
**Pull request by jessemarple**
Fixes #5006

Minor UI fixes to include: 

* Removes specificity to LI class concerning new pflowlist OL LIs. The creation of new Workflow steps didn't include a class that was added to existing steps. The classes specificity was unnecessary and didn't impact other UI 
* Fixes dropdown padding issue in flowlist LIs
* Removes loading() and emptyHTML() from edit/save Options -> Job Workflow UI
* Fixes misalignment of text in option listing
* Replaces Pale with Smoke grey on Jobs page

### CODE REVIEW

**Comment by gschueler** [comment]
Can you post screenshots?

Guidelines issues:

* jobedit.js was also reformatted making it hard to discern the actual changes.
* please reference the fixed issue number https://github.com/rundeck/rundeck/wiki/Github-Guidelines#bug-fixes

**Comment by jessemarple** [comment]
I've updated the name of the pull request.

I will not be able to 'unformat' jobedit.js. The original code was improperly formatted according to JavaScript standards and the IDE updated it. Going forward, I will make sure that prior to making changes on files that are known to be improperly formatted that a discrete commit will be made covering only the formatting changes.

**Comment by jessemarple** [comment]
There's a weird issue that didn't pop up when this was first committed.

Screen Shot 2019-07-01 at 9 14 12 AM

The Workflow steps UI edit dropdown seems to have attracted a new set of styles that are not what is meant for that UI. Do not merge this PR until that has been resolved.

**Comment by jessemarple** [comment]
This makes sense now, as the dropdown is a list item and the workflow steps are also list items. Working on a fix now.

**Comment by jessemarple** [comment]
The strange UL.dropdown > LI issue that occured because of changes to the Workflow steps OL>LI has been resolved.

An alignment issue was resolve that caused the "Add Step" card to appear 20px wider than the OL>LI Workflow step above. While not incorrect (as it's an OL with displayed numbers inside), aesthetically it seems off. 20px of margin were added to give it the same width as the LI above.

**Comment by jessemarple** [comment]
Screengrabs:

Screen Shot 2019-07-01 at 10 53 35 AM
Screen Shot 2019-07-01 at 10 51 17 AM

**Comment by gschueler** [comment]
> Use the phrase "Fixes #123" either in the commit message or the PR description

**Pull request merged**
