### PR TITLE
[build] Upgrade to gradle 4.8 compatible project structure. 

### PR DESCRIPTION
**Pull request by sjrd218**
This is required for future Grails upgrade work.

### CODE REVIEW

**Comment by gschueler** [comment]
i'm curious what the gradle requirement is for this change? the sub project name can't be modified as we did before?

**Comment by gschueler** [comment]
is it breaking to rename the dir? 😨

**Comment by sjrd218** [comment]
@gschueler Here's a link to my gradle issue regarding this. https://github.com/gradle/gradle/issues/8884

**Comment by gschueler** [comment]
I wonder if we can simply modify the rundeckapp build to change the artifact name to "rundeck", instead of having to this kind of thing, and leave the gradle project named "rundeckapp".  the changes here mean any new gradle project under rundeckapp/ has to have its path explicitly defined in the settings.gradle

**Comment by sjrd218** [comment]
I'm in favor of the idea. It's been a long time since I looked into the issue, but I believe there were challenges with renaming the build artifact. I abandoned that route for the one we currently have in place. Since we can't keep what we have, it may be worth looking into again.

**Comment by sjrd218** [comment]
@jessemarple I've checked this again and it looks ok to merge to me.

**Pull request merged**
