### PR TITLE
RUN-18: Show date in ISO 8601 format in the GUI #6582

### PR DESCRIPTION
**Pull request by nvalenzuela20**
Fix: https://github.com/rundeck/rundeck/issues/6582

**Is this a bug fix, or an enhancement? Please describe.**
The start date, complete date and tooltip were being printed on the page without the date in ISO 8601 format

image
image

**Describe the solution you've implemented**
Page rendering was modified to print the timestamp the date in ISO 8601 format correctly

image
image

### CODE REVIEW

**Review by ProTip — COMMENTED** [review]
With `Z` being dropped how would the user know what the absolute time is? ie:
* The server is US Central TZ but the user is in California(PST); would they be able to figure out the absolute(UTC) time?

Changing these times from UTC to a server local time may be very surprising to many users(particularly in such a subtle way as the `Z` being dropped). At a minimum it may be need to be behind a feature flag or configuration; @gschueler ?

**Comment by nvalenzuela20** [comment]
@ProTip 

 I have been assuming the following about timestamps:
- that the timestamps on the database are stored in local server time
- Rundeck on the server is correctly reading this and obtaining a UTC value

Using that, the proposed fix changes the formatting on the page so that timestamps appear in the timezone of the browser that is rendering the page. This is done by passing a UTC timestamp from the server and then parsing and formatting to local time on the client browser. Am I understanding correctly how are timestamps handled by Rundeck?

Yes, I agree that the formatting is confusing, would it be ok then if I change all the timestamp formatting on this page so that its clear what is the timezone that was used to format the time? It could look like this:

2020-10-12T18:37:47 -03:00

**Review by ProTip — COMMENTED** [review]
I believe there may be some confusion over the requirements and behavior. The issue states that there is a need for the time to be displayed in the _servers_ local time.

The taglib addition `formatTimeInLocalTimeZone` will actually render the time in the servers TZ, however this value gets replaced by the knockout binding.

The knockout code will format the time in the _users_ local time, not the servers local time.

I believe we may need to shape up the following:
* What sort of configuration this should go behind
* What local time the time should be formatted in per the original ask(the servers TZ or the users TZ)
* The format for the time in the UI

**Comment by fdevans** [comment]
Based on the open questions for this I'm going to defer it for 3.3.7

**Comment by fdevans** [comment]
Since this PR does not fix the issue and the original PR was done on version 3.3.x I'm going to close this and we will revisit #6582 in the future.

**Pull request closed without merging**
