### PR TITLE
Switch to commonmark-java from markdownj, enable gfm tables extension

### LINKED ISSUE #2690: Global filter : Render formatted data
Issue type: Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.9.2
* install type: launcher
* OS Name/version: WS2012R2
* DB Type/version: MSSQL

**Expected Behavior**
Markdown tables are supported

**Actual Behavior**
Markdown tables are not supported

**How to reproduce Behavior**
echo in a step 
```
| col1 | col2 | col3 | col4  | col5  |
|---|---|---|---|---|
| value1 | value2 | value3 | value4  | value5  |
```
it doesn't render as a table (e.g. in GFM)

| col1 | col2 | col3 | col4  | col5  |
|---|---|---|---|---|
| value1 | value2 | value3 | value4  | value5  |

This could a nice table output with hyperlinks to e.g. other rundeck jobs.

### PR DESCRIPTION
**Pull request by damageboy**
This commit fixes #2690

The main stuff going on here:
* Dump markdownj
* Use commonmark-java + GFM tables extension
* Include a new markdown only CSS that is applied on markdown blocks only...

The rendered markdown is overall pleasant (personal opinion) and appears pretty close to github's own css thanks to the great CSS I found:
image

### CODE REVIEW

**Comment by gschueler** [comment]
Cool, thank you.  Do you have any before/after screenshots of other places in the Markdown codec is used?  (E.g. project Readme/MOTD, option descriptions,...)

**Comment by damageboy** [comment]
I don't.

If you need me to, I'll gladly submit more screenshots...

**Comment by damageboy** [comment]
Let me generate a few screenshots as you suggested with 2.9.3 / this PR

**Comment by ahonor** [comment]
👍

**Comment by damageboy** [comment]
Here is the markdown I used, it contains a table, bullet list, few headings and pre-formatted blocks.
The table has a couple of links embeded for good measure...

```
## Wow

### Such MD

Type=StringFormatBenchmark  Mode=Throughput  Platform=X64

Method|Jit|Median|StdDev|Scaled|Min|Max|Gen 0|Gen 1|Gen 2|Bytes Allocated/Op 
---|---|---|---|---|----|----|---|---|---|----
[Baseline](https://github.com/MendelMonteiro/StringFormatter/blob/master/StringFormatterBench/Program.cs#L39) | LegacyJit | 932.3745 ns | 6.5379 ns |   1.00 | 911.7104 ns | 941.6221 ns | 610.00 |     - |     - |             230.71
[Baseline](https://github.com/MendelMonteiro/StringFormatter/blob/master/StringFormatterBench/Program.cs#L39) |    RyuJit | 936.3304 ns | 6.2145 ns |   1.00 | 929.3742 ns | 950.8991 ns | 629.69 |     - |     - |             238.11
[StringBuffer](https://github.com/MendelMonteiro/StringFormatter/blob/master/StringFormatterBench/Program.cs#L83) | LegacyJit | 824.8445 ns | 4.3413 ns |   0.88 | 817.6467 ns | 834.4629 ns | 133.87 |     - |     - |              52.75
[StringBuffer](https://github.com/MendelMonteiro/StringFormatter/blob/master/StringFormatterBench/Program.cs#L83) |    RyuJit | 887.2168 ns | 8.8965 ns |   0.95 | 869.2266 ns | 910.2819 ns | 143.00 |     - |     - |              56.35


The following test results compare `StringBuilder/StringFormat.AppendFormat` without allocating, but rather reusing a target buffer for the string.
The main point of this test is to confirm that `StringFormatter` is indeed completely allocation-free when such a behavior is desired:


To Do
-----

There is still some work to be done:

- General library cleanup and documentation
- Flesh out the StringView type.
- Unit tests
- Improved error checking and exception messages
- Custom numeric format strings
- Enums
- DateTime and TimeSpan
- Switch to using UTF8 instead of UTF16? Might be nice.
```

Here's github's own rendering of said markdown:

----------
## Wow

### Such MD

Type=StringFormatBenchmark  Mode=Throughput  Platform=X64

Method|Jit|Median|StdDev|Scaled|Min|Max|Gen 0|Gen 1|Gen 2|Bytes Allocated/Op 
---|---|---|---|---|----|----|---|---|---|----
[Baseline](https://github.com/MendelMonteiro/StringFormatter/blob/master/StringFormatterBench/Program.cs#L39) | LegacyJit | 932.3745 ns | 6.5379 ns |   1.00 | 911.7104 ns | 941.6221 ns | 610.00 |     - |     - |             230.71
[Baseline](https://github.com/MendelMonteiro/StringFormatter/blob/master/StringFormatterBench/Program.cs#L39) |    RyuJit | 936.3304 ns | 6.2145 ns |   1.00 | 929.3742 ns | 950.8991 ns | 629.69 |     - |     - |             238.11
[StringBuffer](https://github.com/MendelMonteiro/StringFormatter/blob/master/StringFormatterBench/Program.cs#L83) | LegacyJit | 824.8445 ns | 4.3413 ns |   0.88 | 817.6467 ns | 834.4629 ns | 133.87 |     - |     - |              52.75
[StringBuffer](https://github.com/MendelMonteiro/StringFormatter/blob/master/StringFormatterBench/Program.cs#L83) |    RyuJit | 887.2168 ns | 8.8965 ns |   0.95 | 869.2266 ns | 910.2819 ns | 143.00 |     - |     - |              56.35


The following test results compare `StringBuilder/StringFormat.AppendFormat` without allocating, but rather reusing a target buffer for the string.
The main point of this test is to confirm that `StringFormatter` is indeed completely allocation-free when such a behavior is desired:


To Do
-----

There is still some work to be done:

- General library cleanup and documentation
- Flesh out the StringView type.
- Unit tests
- Improved error checking and exception messages
- Custom numeric format strings
- Enums
- DateTime and TimeSpan
- Switch to using UTF8 instead of UTF16? Might be nice.

-----------

Here are screenshots of the same markdown pasted into rundeck in a bunch of places:

# Project README:
## Before
image

## After

image


# Job description:
## Before
image
## After
image

# Option Description:
## Before
image
## After
image

# Job Output

## Before
image
##  After
image

**Comment by damageboy** [comment]
Is there anything else I can do for this PR?

**Comment by gschueler** [comment]
lgtm, thanks

**Pull request merged**
