### PR TITLE
SCM usability enhancement

### PR DESCRIPTION
**Pull request by jtobard**
### Automatic synchronize on fetch on `git-export` plugin. 
Default `false`, useful in situations where the same repository and branch is used on other projects.
screenshot at feb 26 12-01-14

### Automatic pull on fetch for `git-import` plugin.
Default `true`, should be the default behavior, to be disabled for advanced git users.
screenshot at feb 26 12-02-20

### Clean button 
Only when the plugin is disabled, it performs a real cleanup of the plugin (in git plugin, deletes the repo folder to be created again when the plugin is enabled).

screenshot at feb 26 12-04-22
screenshot at feb 26 12-04-48

### Automatically "initialize-tracking" setup on file pattern

Git Import Setup on configuration
imagen

imagen

### New behavior on commit
The `Push Remotely?` input  is checked by default.
See #2995

imagen

### CODE REVIEW

**Comment by gschueler** [comment]
@jtobard the `test-scm-git-plugin-inputs.sh` test failed

**Comment by jtobard** [comment]
Tested upgrade from 2.10.6 to 2.10.7 with this changes without problem. Any previous problem should be solved using the new Clean button. All the configurations are successfully imported.

**Comment by gschueler** [comment]
good work on docs 👍 @jtobard

**Comment by jtobard** [comment]
Thanks! that was the last commit for this PR, now it's ready.

**Pull request merged**
