### PR TITLE
Fix project picker view all link

### PR DESCRIPTION
**Pull request by ProTip**
**Describe the solution you've implemented**
Add app link for `menuHome` and use this for the link. This should account for `rdbase`.

**Describe alternatives you've considered**
Using `rdbase` as the `href` as it redirects to the projects list. This didn't seem explicit enough..

### CODE REVIEW

**Comment by imad6639** [comment]
tested this with a deployed war in tomcat and as a standalone as a war with a servlet context path and the `View All Projects` issue is resolved.  However, the `Create New Project` has the same issue with redirecting to ${port}:resources/createProject without the servlet context path

**Comment by ProTip** [comment]
@imad6639 I don't see a `Create New Project` link. Is this somewhere else?

image

**Comment by imad6639** [comment]
Seems to be only available when there are no projects

Screen Shot 2021-05-18 at 1 31 31 PM

**Comment by ProTip** [comment]
@imad6639 The most recent commit should address that issue.

**Review by imad6639 — APPROVED** [review]

**Pull request merged**
