### PR TITLE
Sec: Resolve Vulnerabilities in various UI components

### PR DESCRIPTION
**Pull request by mishingo**
**Is this a bugfix, or an enhancement? Please describe.**
Provides a way to manage JS modules and update to latest releases and resolve security vulnerabilities

**Describe the solution you've implemented**
Implement Mix to manage modules from npm and build to designated dir

### Vendoring
The Gradle build has been updated to _vendor_ the files during the build process.

The vendor location is `grails-app/assets/javascripts/vendor`.

JS `//require`s and GSP imports have been updated accordingly.

### CODE REVIEW

**Review by ProTip — CHANGES_REQUESTED** [review]
Currently failing CI/CD. The previous attempt to update to Bootstrap `3.4.x` failed.

The package management infrastructure should be excluded from the Grails asset pipeline.

**Review by ProTip — COMMENTED** [review]
We should probably add instructions on how to update the dependencies in the future.

Is there a good way to verify the source of the deps being checked in? There doesn't seem to be a good way to review these blobs of minified code for security or other issues. Perhaps we could pin the deps and wire the mix process into the Gradle build so the deps are fetched from npm during build?

**Comment by mishingo** [comment]
Agreed tying this into the gradle build is more secure

**Comment by ProTip** [comment]
After discussing with @mishingo I will wire this into the Gradle build and update the PR.

**Review by ProTip — APPROVED** [review]

**Pull request merged**
