### PR TITLE
Fix #4704 Creating a new permission to allow or deny view executions history limiting by job groups

### LINKED ISSUE #4704: Request to limit the Activity view for job executions  (kind: event) based on job groups
Enhancement request to limit the activity view for job executions  (kind: event) for job groups. This is actually not possible, it's only possible to provide access to jobs in a project by job name, UUID or by job group.

Please see the screenshot from the GUI creation feature for events and for jobs.

events
jobs

### PR DESCRIPTION
**Pull request by carlosrfranco**
**Is this a bugfix, or an enhancement? Please describe.**
Enhancement request to limit the activity view for job executions (kind: event) for job groups.

**Describe the solution you've implemented**
I created a new permission type for job to allow or deny history executions for this group/job

**Describe alternatives you've considered**
Before, I added a group or job attributes on resource (kind: event) but it doesn't seem like a good solution since it would affect the permissions to access the activity view too

### CODE REVIEW

**Comment by jtobard** [comment]
This PR has been waiting for a long time, I'm going to try it but can you rebase to master, assign a milestone and the 3.2 label?
Also and example of the ACL woudl be great and connect it to a documentation PR for this enhancement

**Comment by carlosrfranco** [comment]
> This PR has been waiting for a long time, I'm going to try it but can you rebase to master, assign a milestone and the 3.2 label?
> Also and example of the ACL woudl be great and connect it to a documentation PR for this enhancement

ACL example:
`by:
  group: any_group
description: HISTORY_POLICY_EXAMPLE
for:
  job:
  - allow:
    - read
    - view_history
    equals:
      group: some_group
context:
  project: MY_PROJECT
`

**Comment by jtobard** [comment]
I tried build this PR and running local, using the default job viewer ACL and denying the view but I still can see the executions on that group, I'm leaving the ACL here for you to try it.

```
description: Allow groups to list projects
context:
  application: 'rundeck'
for:
  project:
  - allow: read
    match:
      name: '.*'
by:
  group: job_viewer

---

description: Global read access to job_reader role
context:
  project: '.*'
for:
  job:
  - allow: [view]
    match:
      name: '.*'
  - deny:
    - read
    - view_history
    equals:
      group: some_group
  resource:
  - allow: read
    equals:
      kind: event
by:
  group: job_viewer
```

**Comment by gschueler** [comment]
the documentation change was incorrectly merged before the code change, will need to be reverted (https://github.com/rundeck/docs/pull/402) and remade if this is accepted

**Comment by carlosrfranco** [comment]
> design:
> 
>     * justification: why is this change needed? need to reference a feature request or other issue
This change was a enhancement asked by customers and reported by support on an issue so this PR is to fix #4704
> 
>     * expected behavior: what exactly is the new ACL supposed to do?
This new ACL is for a case that customers need to give access only to see executions history for a group of jobs and will not have others permissions for this jobs
>       
>       * You added a new ACL action for jobs; how would the end user apply this? is it meant to be a subset of "view" action?
>       * If it is a subset of "view", what is the expected behavior when only "view_history" is allowed? what if "view" is allowed, and "view_history" is denied?
Yes, this ACL is a subset of "view" and "READ" actions so, if only "view_history" is allowed, the user will be able to see the executions history for the jobs but will not have access to "view" this jobs and, if "view" is allowed and "view_history" is denied, the user will not be able to see the executions history but he can "view" the jobs. On the other hand, if "view" and/or "read" is allowed and "view_history" is omitted, user will be able to see the executions history of the jobs
> 
>     * compatibility: what affect will this change have on existing systems? Is this change drop-in compatible for existing users?
This changes will affect the existing systems requiring the "view_history" action to see the executions history if the user does not have permission to "view" or "read" jobs
> 
> 
> code quality:
> 
>     * javadoc not added for new methods
Added on last commit
> 
> 
> correctness:
> 
>     * jobHistoryAuthorizations method:
>       
>       * REJECTED_DENIED is not addressed. any denied decision overrides any allowed decision for the same action.  If any of the tested action is denied, it should not be allowed even if th user is granted one of the other actions. So simply checking "any are granted" and "not every one is rejected" is not sufficient.  Any action that is has code REJECTED_DENIED should be removed from the GRANTED list.
Fixed on last commit
> 
> 
> efficiency:
> 
>     * the "jobHistoryAuthorizations" retrieves every job name in the project, and tests ACLs against them, however not every query needs to do that.  The set of jobs should be reduced based on the original query
I really agree with you about efficiency on this query but I need to make sure that in the next query, if the job list is changed, the jobs will be retrieved again ACL's will be retested. Is there a good way to do that?
> 
> 
> documentation:
> 
>     * more information is needed in the proposed documentation regarding the expected behavior
Will be created a new PR for docs

**Comment by gschueler** [comment]
restored docs pr https://github.com/rundeck/docs/pull/435

**Pull request merged**
