### PR TITLE
Use master branch of ui trellis

### PR DESCRIPTION
**Pull request by ProTip**
Set ui-trellis dependency to particular commit id

### CODE REVIEW

**Comment by gschueler** [comment]
btw, i wonder if it should use a tag/commit instead of branch name ... the branch is likely to change over time

**Comment by ProTip** [comment]
That makes a lot of sense for releases.

**Comment by ProTip** [comment]
Fixes #4593

**Comment by gschueler** [comment]
@ProTip even for non-release code, since ui-trellis can change outside of rundeck code, it makes sense to set the dependency to a particular tag/commit I think

**Comment by ProTip** [comment]
@gschueler I was thinking for some reason it would be good to get updates on master but.. That does not make sense to me ATM. I've pinned the `ui-trellis` version.

**Pull request merged**
