### PR TITLE
Fixes #1994

### LINKED ISSUE #1994: Debian and CentOS packages have different permissions on config files (/etc/rundeck)
Hi,

I'm running some tests with Rundeck on multiple platforms (Debian and CentOS) and found an inconsistency between Debian and CentOS packages for the config files (/etc/rundeck):

**CentOS**
```bash
[root@9abea52ccc52 ~]# cat /etc/redhat-release 
CentOS release 6.8 (Final)
[root@9abea52ccc52 ~]# ls -lah /etc/rundeck/                                                                                                                                                                                                 
total 56K
drwxrwxr-x  3 rundeck rundeck 4.0K Aug  9 05:33 .
drwxr-xr-x 79 root    root    4.0K Aug  9 05:33 ..
-rw-r--r--  1 rundeck rundeck  738 Aug  3 22:24 admin.aclpolicy
-rw-r--r--  1 rundeck rundeck 1.1K Aug  3 22:24 apitoken.aclpolicy
-rw-r--r--  1 rundeck rundeck  511 Aug  3 22:24 cli-log4j.properties
-rw-r--r--  1 rundeck rundeck 1.3K Aug  3 22:24 framework.properties
-rw-r--r--  1 rundeck rundeck  141 Aug  3 22:24 jaas-loginmodule.conf
-rw-r--r--  1 rundeck rundeck 7.5K Aug  3 22:24 log4j.properties
-rw-r--r--  1 rundeck rundeck 1.8K Aug  3 22:24 profile
-rw-r--r--  1 rundeck rundeck  549 Aug  3 22:24 project.properties
-rw-r--r--  1 rundeck rundeck  986 Aug  3 22:24 realm.properties
-rw-r--r--  1 rundeck rundeck  416 Aug  3 22:24 rundeck-config.properties
drwxrwxr-x  2 rundeck rundeck 4.0K Aug  9 05:33 ssl
```

**Debian**
```bash
root@e16d3f1d19a1:~# lsb_release -a          
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.5 (jessie)
Release:        8.5
Codename:       jessie
root@e16d3f1d19a1:~# ls -lah /etc/rundeck/
total 56K
drwxr-xr-x   3 root    root    4.0K Aug  9 05:35 .
drwxr-xr-x 113 root    root    4.0K Aug  9 05:35 ..
-rw-r-----   1 rundeck rundeck  738 Aug  3 22:24 admin.aclpolicy
-rw-r-----   1 rundeck rundeck 1.1K Aug  3 22:24 apitoken.aclpolicy
-rw-r-----   1 rundeck rundeck  511 Aug  3 22:24 cli-log4j.properties
-rw-r-----   1 rundeck rundeck 1.3K Aug  3 22:24 framework.properties
-rw-r-----   1 rundeck rundeck  141 Aug  3 22:24 jaas-loginmodule.conf
-rw-r-----   1 rundeck rundeck 7.5K Aug  3 22:24 log4j.properties
-rw-r-----   1 rundeck rundeck 1.8K Aug  3 22:24 profile
-rw-r-----   1 rundeck rundeck  549 Aug  3 22:24 project.properties
-rw-r-----   1 rundeck rundeck  986 Aug  3 22:24 realm.properties
-rw-r-----   1 rundeck rundeck  416 Aug  3 22:24 rundeck-config.properties
drwxr-xr-x   2 root    root    4.0K Aug  9 05:35 ssl
```

As you can see CentOS permissions are `0644` for files and `0775` for __/etc/rundeck/ssl__ folder, while Debian permissions are `0640` for files and `0755` for __/etc/rundeck/ssl__ folder.

So I think we should do `0640` for files and `0750` for __/etc/rundeck/ssl__ folder.

I will push a PR in some minutes to fix this so you can check (I have tested with Travis and all tests passed ok)

Thanks!

### PR DESCRIPTION
**Pull request by amontalban**
Fixes #1994.

### CODE REVIEW

**Comment by amontalban** [comment]
Travis is having issues today so that might be the cause of the failed test, worked for me here:

https://travis-ci.org/devopxteam/rundeck/builds/150935142

**Comment by gschueler** [comment]
grr, travis 😬

**Comment by gschueler** [comment]
I think if you rebase on master it should build now via travis

**Comment by amontalban** [comment]
Done, let's see how it goes :)

**Comment by amontalban** [comment]
Wooohoo! Worked.

**Comment by amontalban** [comment]
@gschueler does it look good to you? Let me know if you need anything. Thanks!

**Comment by gschueler** [comment]
thanks!

**Pull request merged**
