### PR TITLE
UI tweaks 3.1: part B

### PR DESCRIPTION
**Pull request by gschueler**
WIP: more UI changes for 3.1

Todo:
- Project Dashboard
  - [ ] <strike>add activity view</strike> - not including
  - [ ] <strike>add now running</strike> - not including
- Job Run view page
  - [ ] reposition "run job later" - fix ui
  - [ ] improve usefulness of Activity view
  - [ ] reposition Runbook?
- Navigation
  * [ ] drop down navigation for main links
  * [ ] improve project selector
  * [ ] "admin" menu combines Project/System into sub-drop-downs?
- MOTD
  - [x] change to use header icon when motd is present on non-dashboard pages
  - [x] respect project config for motd display
- [x] Activity page: update to vue
  - [x] query input
  - [x] url parameters mapped to query params
  - [x] reorder columns
  - [x] now running
  - [x] auto refresh
  - [x] save/edit user filters

stretch:
- [ ] Project Config page: default node exec/file copier selection should be improved
- [ ] Job Edit page: WF step picker, Notification config should be improved

Issues:
- [ ] Execution view page: output loading progress bar is not full width (firefox,chrome)
- [ ] [`Edit job dropdown hangs with Loading`](https://github.com/rundeck/rundeck/pull/4822#issuecomment-492447762)
- [ ] [`execution history clean label appears to need a label:`](https://github.com/rundeck/rundeck/pull/4822#issuecomment-492449730)
- [ ] [`"Waiting" appears to be hidden a smidge during job execution...`](https://github.com/rundeck/rundeck/pull/4822#issuecomment-492451724)

### CODE REVIEW

**Comment by skywalke34** [comment]
Edit job dropdown hands with _Loading_
image

**Comment by skywalke34** [comment]
Configure Project - execution history clean label appears to need a label:
image

**Comment by skywalke34** [comment]
"Waiting" appears to be hidden a smidge during job execution... 
image

**Comment by ahonor** [comment]
The "Workflow" graph view for execution show page should in the View drop down menu like Nodes and Output.

**Comment by gschueler** [comment]
next set of changes: https://github.com/rundeck/rundeck/pull/4858

**Pull request merged**
