### PR TITLE
support chinese 

### PR DESCRIPTION
**Pull request by chenlingmin**

### CODE REVIEW

**Comment by tigerlee** [comment]
@gschueler These pull requests were not fully merge into master. You just picked one commit from the PRs. So that when I choose 'Simplified Chinese' on the language combo box, nothing changed at all.

I don't know whether those PRs are correct changes or not. Before these changes were confirmed, I suggest you should remove 'Simplified Chinese' (`简体中文` in Chinese) option in language list.

**Comment by beebird** [comment]
not really support Simplified Chinese....

**Comment by chenlingmin** [comment]
Sorry, I don't have time to maintain Chinese, And English is universal 😂

**Comment by DrHA** [comment]
牛哥 能不能指导下如何汉化？我想自己试下汉化 谢谢您啦

**Pull request merged**
