### PR TITLE
Don't allow starting rundeckd multiple times.

### PR DESCRIPTION
**Pull request by PriceChild**

### CODE REVIEW

**Comment by gschueler** [comment]
thank you!

**Comment by PriceChild** [comment]
@gschueler No probs.

Sorry, forgot to mention I've tested it on my centos6 install but haven't tested the debian init script... it looks like it should work but someone else should please!

**Comment by gschueler** [comment]
Hi, thank you for submitting this change.  👏  I apologize that it was not addressed in a timely fashion 😢, we are working to improve the way we handle PRs. 

If you are still interested in proposing this change, please feel free to reopen the request.  Since it has been some time since it was opened, your code might be now out of date.  If so, please try to rebase your changes on the latest `master` branch.

Thank you!

**Comment by PriceChild** [comment]
@gschueler Looks like the affected files haven't changed since I proposed this change. I don't see to be able to reopen the merge request but the patch should still cleanly apply?

**Comment by gschueler** [comment]
@PriceChild the debian rundeckd script has changed

**Comment by PriceChild** [comment]
Silly me, looks like I was looking at my own fork by mistake!

So the debian version is conflicting because someone else has added a similar check. I've removed that.

It looks like the centos version didn't get a similar check added, so I'll continue to suggest what I originally did.

**Comment by gschueler** [comment]
I extended your change with some tests and merged in #3468  
Thanks!

**Pull request closed without merging**
